steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/exprec:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/exprec:latest',
        '--cache-from', 'gcr.io/$PROJECT_ID/exprec:latest',
        '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
        '.'
  ]
images: ['gcr.io/$PROJECT_ID/exprec:latest']
