options:
  logging: CLOUD_LOGGING_ONLY  # Logs are only available in Google Cloud Console (Cloud Logging)

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/exprecapp:latest || exit 0']

- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/exprecapp:latest',
        '--cache-from', 'gcr.io/$PROJECT_ID/exprecapp:latest',
        '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
        '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
        'push', 'gcr.io/$PROJECT_ID/exprecapp:latest'
  ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy exprecapp \
      --image gcr.io/$PROJECT_ID/exprecapp:latest \
      --region europe-west4 \
      --platform managed \
      --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/exprecapp:latest'
